backend:
  name: github
  repo: HarryFray/Portfolio
media_folder: static/assets
public_folder: /assets
collections:
  - name: project
    label: project
    folder: src/projects
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: 'subTitle', label: 'Sub Title'}
      - { name: body, label: Body, widget: markdown }
      - { 
        name: "backgroundimage",
        label: "Featured Image",
        widget: "image",
        default: "/src/images",
 }