backend:
  name: github
  repo: HarryFray/Portfolio
media_folder: src/images
# public was just source if something goes wrong with next upload
public_folder: src/images
collections:
  - name: project
    label: project
    folder: src/projects
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: client, label: Client }
      - { name: timeline, label: Timeline }
      - { name: primaryRole, label: Primary Role }
      - { name: contributers, label: Contributers }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: subTitle, label: Sub Title}
      - { name: body, label: Body, widget: markdown }
      - { name: tech, label: Tech }
      - { name: externalLink, label: External Link, required: false }
      - { 
        name: backgroundimage,
        label: Featured Image,
        widget: image,
        default: src/images,
 }
