backend:
  name: github
  repo: HarryFray/Portfolio
media_folder: static/assets
public_folder: /assets
collections:
  - name: project
    label: project
    folder: src/projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: 'subTitle', label: 'subTitle'}
      - { name: body, label: Body, widget: markdown }